### PR TITLE
Sync comments with Scratch updates for rendering, events, minimize, etc

### PR DESCRIPTION
**Pull request by shakao**
Syncing with Scratch comments. Most files are referenced from the file with the same name in [the Scratch repo](https://github.com/LLK/scratch-blocks/tree/develop/core), except workspace_comment_events.js (PXT/Blockly) which maps to [comment_events.js](https://github.com/LLK/scratch-blocks/blob/develop/core/comment_events.js) (Scratch).

Main areas where our code diverges from Scratch (I tried to mark most with "PXT Blockly" comments) are: 
- Uneditable comments (Scratch doesn't have these)
- Block-level comments (we use comments.js, Scratch uses ScratchBlockComments (scratch_block_comments.js) )
- Small rendering differences

Fixes Safari rendering issues (Microsoft/pxt-microbit/issues/1481, Microsoft/pxt-microbit/issues/755)

### CODE REVIEW

**Comment by abchatra** [comment]
Getting bored in the bootcamp ;-)?

**Comment by shakao** [comment]
Some of this was from last week!

**Comment by riknoll** [comment]
This is a lot of changes, I'm not really sure how to review it! Maybe you can upload a build that we can try out? I'll send you some instructions

**Comment by shakao** [comment]
Build here! https://makecode.microbit.org/app/595e7b6e92b318f3e1951e5c7dc02fe8a47f666f-a32ccc4874

And yeah, I wish there was a way to do a three-way diff with the relevant Scratch files or something... or if anyone has suggestions for breaking it up into smaller chunks? The bubble-related changes are potentially standalone but that still leaves a big chunk of workspace comment changes.

**Comment by abchatra** [comment]
Seems like some issues with the build in Edge
image
In Chrome:
image

**Review by riknoll — APPROVED** [review]

**Pull request merged**
