### PR TITLE
Merge Blockly changes through July 2021

### PR DESCRIPTION
**Pull request by shakao**
The last 4-5 commits are the changes I made to sync our fork. I preferenced Blockly's changes wherever possible; there wasn't anything huge in this update:

- Some stuff from connection.js moved to connection_checker.js
- Some updates to the toolbox and flyout--we don't use the Blockly toolbox at all so I took their version that entire file
- Changes to the context menu
- Changes to the build (mostly moving stuff into files)

These two are probably the commits with the most changes:
https://github.com/microsoft/pxt-blockly/commit/ab88addbd58af8318305ffc09b5fcffdd0d035e1
https://github.com/microsoft/pxt-blockly/commit/fe25bf3dbee972532d77ea1957c8168533ef2833

And here are two builds if you'd prefer to click around: 
https://arcade.makecode.com/app/4ba2fbb285bc77c46b8c78ab687e46b37d486d80-114181538c
https://makecode.microbit.org/app/34b3d2fce28db46856e284436ece6c2ff11aeb37-3cca8aed21

### CODE REVIEW

**Review by livcheerful — APPROVED** [review]
🔍looks like code

**Review by jwunderl — APPROVED** [review]

**Comment by abchatra** [comment]
Bump the major version after merging this.

**Comment by riknoll** [comment]
Got an exception with comments:

```
pxtapp.js:3544 TypeError: b.getCommentText is not a function
    at maybeAddComment (pxtblockly.js:5426)
    at compileExpression (pxtblockly.js:4429)
    at compileControlsIf (pxtblockly.js:4566)
    at compileStatementBlock (pxtblockly.js:4937)
    at compileStatements (pxtblockly.js:5019)
    at compileStartEvent (pxtblockly.js:4885)
    at compileStatementBlock (pxtblockly.js:4976)
    at pxtblockly.js:5185
    at Array.forEach (<anonymous>)
    at compileWorkspace (pxtblockly.js:5178)
```

I think it may be related to having an if statement with an empty conditional

**Comment by riknoll** [comment]
Also get some weird results when switching editors. Blockly workspace turns invisible (but you can still drag blocks). Resizing the window so that the sim disappears fixes it.

**Comment by shakao** [comment]
@riknoll nice finds! one pxt-side fix, one here. updated builds as well:

https://arcade.makecode.com/app/4ba2fbb285bc77c46b8c78ab687e46b37d486d80-114181538c
https://makecode.microbit.org/app/34b3d2fce28db46856e284436ece6c2ff11aeb37-3cca8aed21

**Pull request merged**
